CREATE DATABASE Moodvies;

CREATE TABLE Users (
PRIMARY KEY (UserID),
Name VARCHAR(50) NOT NULL,
Age INT NOT NULL,
Email VARCHAR(75) NOT NULL,
Password VARCHAR(50) NOT NULL);

CREATE TABLE Genre (
PRIMARY KEY (GenreID),
Genre VARCHAR(50) NOT NULL);

CREATE TABLE Moods (
PRIMARY KEY (MoodID),
Mood VARCHAR(50) NOT NULL);

CREATE TABLE Title (
PRIMARY KEY (TitleID),
Title VARCHAR(200) NOT NULL);

CREATE TABLE Entries (
PRIMARY KEY (EntryID),
FOREIGN KEY (UserID) REFERENCES Users,
FOREIGN KEY (MoodID) REFERENCES Moods,
FOREIGN KEY (GenreID) REFERENCES Title);